name: fyp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1
  # sdk: ">=3.6.1 <4.0.0"  # Ensuring compatibility with Flutter 3.6+

dependencies:
  flutter:
    sdk: flutter

  # Common dependencies from both files
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  fl_chart: ^0.64.0
  image_picker: ^1.0.7
  http: ^1.3.0
  shared_preferences: ^2.5.2
  jwt_decoder: ^2.0.1
  async: ^2.11.0
  path: ^1.9.0
  flutter_image_compress: ^2.4.0
  image: ^4.1.3
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  permission_handler: ^11.4.0
  location: ^8.0.0
  get_ip_address: ^0.0.7
  location_manager_flutter: ^0.1.3
  flutter_exif_rotation: ^0.5.2
  socket_io_client: ^3.0.2
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  intl: ^0.19.0
  cnic_scanner: ^0.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Kept the latest version

flutter:
  uses-material-design: true

  assets:
    # Merged assets list from both configurations
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/logo.png
    - assets/images/e.png
    - assets/images/j.webp
    - assets/images/c.png
    - assets/images/m.png
    - assets/images/1a.jpg
    - assets/images/1c.png
    - assets/images/1d.png
